image: debian

stages:
  - test

before_script:
  - apt update
  - apt install -y autoconf make gcc pkg-config check

test:
  stage: test
  script:
    - sh autogen.sh
    - sh configure
    - make test
