.TH "iast" "1" "16 October 2020" "sanskrit-iast" "Sanskrit Transliteration"

.SH NAME
.B iast
- a helper for Sanskrit transliteration


.SH SYNOPSIS
.SY iast
.OP -h
.OP -v
.RB [ -f
.IR FILE ]...\&
.RB [ -r " |"
.BR -c " |"
.BR -e ]
.RI [ "TEXT ARGUMENTS" ]...
.YS


.SH DESCRIPTION
\fBiast\fR is a tool for the lossless transliteration of Sanskrit terms written
in Devanagari into Latin using the IAST scheme (International Alphabet of
Sanskrit Transliteration).

The program allows to perform transliteration either on all non-option
arguments or on whole files specified by the \fB-f\fR option. By default, it
performs transliteration from Devanagari to a corresponding romanised version,
but using the \fB-r\fR switch, reverse transliteration can be performed, converting
romanised texts back into Devanagari.


.SH OPTIONS
.B \-f
.I FILE
.RS 4
Input file for processing.
.RE

.B \-r
.RS 4
Use reverse transliteration (from Latin to Devanagari).
.RE

.B \-c
.RS 4
Transcript a Devanagari text into Czech.
.RE

.B \-e
.RS 4
Convert Velthuis scheme text to IAST representation
.RE

.B \-h
.RS 4
Show usage information and exit.
.RE

.B \-v
.RS 4
Show version number and exit.
.RE


.SH ENCODING
When the flag \fB-e\fR is set on, the program converts strings encoded using
the Velthuis scheme (purely ASCII-encoded strings) into the special characters
of the IAST alphabet. For example, it can convert ‘sa.msk.rtam’ to ‘saṃskṛtam’
or ‘"saastram’ to ‘śāstram’.

The encoding scheme is based on the following principle: the characters ‘.’,
‘"’ and ‘~’ are considered to be modifiers that modify the letter that stands
after the modifier. For example, if the string to be encoded contains ‘.t’,
it will be encoded as ‘ṭ’, the sequence ‘~n’ as ‘ñ’ and so on. Long vowels are
marked by doubled letter corresponding to the vowel; thus ‘aa’ is encoded to
‘ā’, ‘.rr’ to ‘ṝ’ and so on.


.SH AUTHOR
Copyright (c) 2018, 2020  Vlasta Vesely <vlastavesely@protonmail.ch>


.SH REPORTING BUGS
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you do and the bug is still present, you can
report it using either the issues tracker on GitLab or GitHub.

.RS 4
GitLab: <https://gitlab.com/vlastavesely/sanskrit-iast/issues>
.br
GitHub: <https://github.com/vlastavesely/sanskrit-iast/issues>
.RE


.SH LICENSE AND WARRANTY
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.


.SH SEE ALSO
More information on the encoding schemes can be found on Wikipedia:

.RS 4
IAST scheme: <https://en.wikipedia.org/wiki/IAST>
.br
Velthuis scheme: <https://en.wikipedia.org/wiki/Velthuis>
.RE
