.TH "iast" "1" "02 March 2023" "sanskrit-iast" "Sanskrit Transliteration"

.SH NAME
.B iast
- a program for Sanskrit transliteration


.SH SYNOPSIS
.SY iast
.RB [ -f
.IR FILE ]...\&
.RI [ "TEXT ARGUMENTS" ]...
.br
.SY iast
.B -r
.RB [ -f
.IR FILE ]...\&
.RI [ "TEXT ARGUMENTS" ]...
.br
.SY iast
.B -e
.RB [ -f
.IR FILE ]...\&
.RI [ "TEXT ARGUMENTS" ]...
.YS


.SH INTRODUCTION
.B iast
is a tool for the lossless transliteration of Sanskrit texts from Devanagari
to the Latin alphabet using the
.I IAST
scheme (International Alphabet of Sanskrit Transliteration). It should be
noted that as the
.I IAST
standard does not handle the Devanagari characters with the diacritic marks
(e.g., the nukta), it cannot be used to transliterate modern Hindi texts.
However, there is an one-way transcription mode that can be used to transcript
Devanagari Hindi texts to the Latin alphabet (see below).


.SH OPTIONS
.BR \-f
.IR FILE ,
.B \-\-file
.I FILE
.RS 4
The input file for the transliteration. A plain text file containing a
.BR UTF-8 (7)
string is expected. When the
.I FILE
is
.BR - ,
the contents of the standard input shall be read.
.RE

.BR \-o
.IR FILE ,
.B \-\-output
.I FILE
.RS 4
The output file. When the
.I FILE
is not specified, the standard output shall be used.
.RE

.BR \-r ,
.B \-\-reverse
.RS 4
Use reverse transliteration (from Latin to Devanagari).
.RE

.BR \-c ,
.B \-\-czech
.RS 4
Transcript a Devanagari text into Czech using only the characters of the Czech
alphabet (an experimental feature).
.RE

.BR \-H ,
.B \-\-hindi
.RS 4
Transcript a Hindi text from Devanagari into the Latin alphabet. This mode is
irreversible as it uses just phonetic transcription instead of lossless
transliteration.
.RE

.BR \-e ,
.BR \-\-encode ,
.BR \-\-velthuis
.RS 4
Convert a plain
.BR ASCII (7)
string to the
.I IAST
representation using the
.I Velthuis
scheme.
.RE

.BR \-k ,
.BR \-\-harvard ,
.BR \-\-kyoto
.RS 4
Convert a plain
.BR ASCII (7)
string to the
.I IAST
representation using the
.I Harvard-Kyoto
scheme.
.RE

.BR \-a ,
.B \-\-ascii
.RS 4
Output
.I Velthuis
encoding rather than
.I IAST
characters.
.RE

.BR \-d ,
.B \-\-devanagari
.RS 4
When encoding, output Devanagari rather than
.I IAST
characters.
.RE

.BR \-h ,
.B \-\-help
.RS 4
Show the usage information and exit.
.RE

.BR \-v ,
.B \-\-version
.RS 4
Show the version number and exit.
.RE


.SH DESCRIPTION
.SS Transliteration
The program allows to perform transliteration either on all non-option
arguments or on whole files specified by the
.B -f
option. By default, the program
performs transliteration from Devanagari to a corresponding romanised version,
but using the
.B -r
switch, reverse transliteration can be performed, converting romanised texts
back into Devanagari.


.SS Transcription
Alternatively, there are two transcription modes.
When the
.B -H
flag is used, the input will be handled as a Hindi text and transcripted into
the Roman alphabet, ignoring the
.I IAST
diacritics.

Alternatively, when the flag
.B -c
is used, the input can be transcripted for usage in the Czech language,
limiting the used characters to the common characters of the Czech alphabet
and applying some phonetic changes.

Note: neither of the transcription modes is unambiguous and it is therefore
not possible to recover the original Devanagari version again.


.SS Velthuis Encoding
When the flag
.B -e
is set on, the program converts strings encoded using the
.I Velthuis
scheme (purely
.IR ASCII -encoded
strings) into the special characters
of the
.I IAST
alphabet. For example, it can convert ‘sa.msk.rtam’ to ‘saṃskṛtam’
or ‘"saastram’ to ‘śāstram’.

The encoding scheme is based on the following principle: the characters ‘.’,
‘"’ and ‘~’ are considered to be modifiers that modify the letter that stands
after the modifier. For example, if the string to be encoded contains the ‘.t’
sequence, it will be encoded as ‘ṭ’, the sequence ‘~n’ as ‘ñ’ and so on. Long
vowels are marked by doubled letter corresponding to the vowel; thus ‘aa’ will
be encoded to ‘ā’, ‘.rr’ to ‘ṝ’ and so on.


.SH SEE ALSO
.BR ascii (7),
.BR utf8 (7),
.I http://mirrors.ctan.org/language/devanagari/velthuis/doc/manual.pdf


.SH FURTHER INFORMATION
More information on Devanagari and the encoding schemes can be found on
Wikipedia:

.RS 2
.I https://en.wikipedia.org/wiki/Devanagari
- the Devanagari script,
.br
.I https://en.wikipedia.org/wiki/IAST
- the IAST scheme,
.br
.I https://en.wikipedia.org/wiki/Velthuis
- the Velthuis scheme.
.br
.I https://en.wikipedia.org/wiki/Harvard-Kyoto
- the Harvard-Kyoto scheme.
.RE


.SH REPORTING BUGS
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you are and the bug is still present, you can
report it on the GitHub issues tracker:
.IR https://github.com/vlastavesely/sanskrit-iast/issues .


.SH LICENSE AND WARRANTY
Copyright © 2018-2022  Vlasta Vesely
.RI < vlastavesely@protonmail.ch >.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
