iast(1)
=======
:manmanual: sanskrit-iast

NAME
----
iast - a helper for Sanskrit transliteration


SYNOPSIS
--------
*iast* [*-h*] [*-v*] [*-f* 'FILE']... [*-r* | *-c* | *-e*] ['TEXT ARGUMENTS']...


DESCRIPTION
-----------
*iast* is a tool for the lossless transliteration of Sanskrit terms written in
Devanagari into Latin using the IAST scheme (International Alphabet of Sanskrit
Transliteration).

The program allows to perform transliteration either on all non-option
arguments or on whole files specified by the *-f* option. By default, it
performs transliteration from Devanagari to a corresponding romanised version,
but using the *-r* switch, reverse transliteration can be performed, converting
romanised texts back into Devanagari.


OPTIONS
-------
*-f* 'FILE'::
Input file for processing.

*-r*::
Use reverse transliteration (from Latin to Devanagari).

*-c*::
Transcript a Devanagari text into Czech.

*-e*::
Convert a symbolic ASCII(7) text to IAST representation.

*-h*::
Show usage information and exit.

*-v*::
Show version number and exit.


ENCODING
--------
When the flag '-e' is set on, the program converts purely ASCII-encoded strings
into the special characters of the IAST alphabet. For example, it converts
"sam.skr.tam" to "saṃskṛtam" or "s,a-stram" to "śāstram".

The encoding scheme is based on the following principle: characters "-", ".",
"," and "~" are considered to be modifiers that modify a letter that stands
before the modifier. For example, if the string to be encoded contains "a-",
it will be encoded as "ā" and the sequence "n~" as "ñ" and so on. The only
exception from the rule is the letter "n" because it can be encoded both with
an over-dot (ṅ) and under-dot (ṇ). For the over-dot variant, the conversion
sequence is "n^.".

Alternatively, the Czech characters "á", "í", "ú", "š" and "ň" can be used as
shortcuts to encode the letters "ā", "ī", "ū", "ś" and "ñ" respectively.


AUTHOR
------
Copyright (c) 2018, 2020  Vlasta Vesely <vlastavesely@protonmail.ch>


REPORTING BUGS
--------------
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you do and the bug is still present, you can
report it using either the issues tracker on GitLab or GitHub.

GitLab: <https://gitlab.com/vlastavesely/sanskrit-iast/issues> +
GitHub: <https://github.com/vlastavesely/sanskrit-iast/issues>


LICENSE AND WARRANTY
--------------------
This software is released under the terms of the GPL license version 2 as
published by the Free Software Foundation.
See <https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt> for more details.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
